@startuml "Transfer Flow (L2 -> L2)"
skinparam style strictuml

|User|
start
:Sign Transfer TX;

|L2 Server|
:Validate Transaction;
:Update L2 State; (Deduct Balance, Increase Nonce);
:Append to Transaction List;

|L2 Server|
:Group Transactions into Batch;
:Generate ZK Proof;

|L2 Server|
:Publish DA Blobs;
|Archive Node|
:Store DA Blobs;
:Return DA_Commitment;
|L2 Server|
:Submit Proof and DA_Commitment;
|L1 Server|
:checkDAAvailability(DA_Commitment);
:Verify ZK Proof;
:Update State Root & DA Root;
|L2 Server|
:Snapshot 'proven_accounts';

stop
@enduml